load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "BitsetControllerAVX_lib",
    srcs = ["BitsetControllerAVX.cpp"],
    hdrs = ["BitsetControllerAVX.h"],
    visibility = [
        "//tests/lib/BitsetControllerAVX:__pkg__",
    ],
)