load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test_BitsetController_lib",
    srcs = ["test.cpp"],
    deps = [
        "//lib/BitsetController:BitsetController_lib",
        "//tools/catch:catch2",
    ],
)